config/routes.rb
Rails.application.routes.draw do
  root 'mindshaft_pages#home'

  get 'mindshaft_pages/about'
  
  get 'about' => 'mindshaft_pages#about'
  get 'features' => 'mindshaft_pages#features'
  get 'media' => 'mindshaft_pages#media'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mindshaft_pages_controller.rb
class MindshaftPagesController < ApplicationController
  def home
    @screenshots = Dir.glob("app/assets/images/dws/screenshots/*.png").sort
    @gifs = Dir.glob("app/assets/images/dws/gifs/*.gif")
  end

  def about
  end

  def features
  end

  def media
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mindshaft_pages_helper.rb
module MindshaftPagesHelper
end

app/views/layouts/_about.html.erb
<div class="wrapper">
  <div class="content">
    <h2>About Demons With Shotguns</h2>
    <p>
        <%= image_tag("shotgun600.png", alt: "Weapon of choice!") %>
        <p>
            <%= image_tag("angelSmoking300.gif") %>
            <%= image_tag("preacherPraying300.gif") %>
            <%= image_tag("demonTaunt300.gif") %>
            <%= image_tag("deathTaunt300.gif") %>
        </p>
    </p>

    <p>
        The battle between Heaven and Hell has been going on for so long,
        no on really remembers why, let alone when, it started. Alas, both sides
        are desperate for souls that can be used to strengthen their numbers.
        Their desperation takes them to the mortal realm, where Angels
        and Demons fight for the souls of mankind.
    </p>

    <p>
        Demons with Shotguns is a competitive platformer featuring
        old school, fast paced, twitch style arena shooting action
        where you battle for the souls of your friends!
    </p>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="theater">
  <div class="game-title-outer">
    <%= image_tag "gif1.gif", style: "width: 75%;" %>
  </div>
</div>

app/views/layouts/_landing.html.erb
<div class="wrapper">
  <div class="content">
    <h1 class="game-title-inner">DEMONS<br/><span style="font-size: 0.6em">WITH</span><br/>SHOTGUNS</h1>
    <h2>A battle for souls</h2>
    <p>
      Up to four players will fight against each other in multiple game modes,
      including free-for-all and team based modes.
    </p>
    <p>
      Armed with a powerful double barrel shotgun, blast your way through your
      opponents, unleasing their souls for you to collect!
    </p>

    <h2>Coming to Steam Greenlight<br/>January 2015</h2>

    <p>
      <%= link_to image_tag("demoButton2.png", alt: "Play the web demo!"), 'http://www.mindshaftgames.com/demo/' %>
    </p>

    <p>
      <a href="http://www.indiedb.com/games/demons-with-shotguns"
        title="View Demons with Shotguns on Indie DB" target="_blank">
        <img src="http://button.indiedb.com/popularity/medium/games/34672.png" alt="Demons with Shotguns" />
      </a>
    </p>
  </div>
</div>

app/views/layouts/_media.html.erb
<div class="wrapper">
  <div class="content">
  <!--  <div class="column">-->
  <!--    <iframe width="560" height="315" src="//www.youtube.com/embed/oiCyhSbrsTQ" frameborder="0" allowfullscreen></iframe>-->
  <!--  </div>-->
  <!--  <div class="column">-->
  <!--    <iframe width="560" height="315" src="//www.youtube.com/embed/Yfjse77cjXk" frameborder="0" allowfullscreen></iframe>-->
  <!--  </div>-->
    <% @screenshots.each do |image| %>
      <div class="column highlight highlight-one">
        <%= link_to image_tag("dws/screenshots/#{image.split('/').last}"), image_path("dws/screenshots/#{image.split('/').last}"), { 'data-lightbox' => 'screenshots', :class => 'image image-full' } %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="row navbar-body">
  <nav class="navbar navbar-inverse">
    <ul class="nav navbar-nav">
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Features", features_path %></li>
      <li><%= link_to "Media", media_path %></li>
    </ul>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demons with Shotguns™ - A MindShaft Game</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/mindshaft_pages/about.html.erb
<div class="wrapper">
    <div class="col-centered">
        <h2>About Demons With Shotguns</h2> 
        <p>
            <%= image_tag("shotgun600.png", alt: "Weapon of choice!") %>
            <p>
                <%= image_tag("angelSmoking300.gif") %>
                <%= image_tag("preacherPraying300.gif") %>
                <%= image_tag("demonTaunt300.gif") %>
                <%= image_tag("deathTaunt300.gif") %>
            </p>
        </p>
    </div>
    
    <div class="content col-centered">
        <p>
            The battle between Heaven and Hell has been going on for so long,
            no on really remembers why, let alone when, it started. Alas, both sides
            are desperate for souls that can be used to strengthen their numbers.
            Their desperation takes them to the mortal realm, where Angels
            and Demons fight for the souls of mankind.
        </p>
        
        <p>
            Demons with Shotguns is a competitive platformer featuring
            old school, fast paced, twitch style arena shooting action
            where you battle for the souls of your friends!
        </p>
    </div>
</div>

app/views/mindshaft_pages/home.html.erb
<%= render 'layouts/header' %>
<div class="landing">
    <%= render 'layouts/landing' %>
</div>
<div class="about">
    <%= render 'layouts/about' %>
</div>
<div class="media_">
    <%= render 'layouts/media', :screenshots => @screenshots, :gifs => @gifs %>
</div>